export const API_ROUTES = {
  public: {
    topic: (slug: string) => '/public/topics/' + slug,
    topics: '/public/topics/',
    posts: '/public/posts',
    post: (slug: string) => '/public/posts/' + slug,
    comments: '/comments',
    ads: '/public/ads',
    ads_click: (id: string) => `/public/ads/${id}/clicks`,
    collection: (slug: string) => '/public/collections/' + slug,
    feed: (slug: string) => '/public/feeds/' + slug,
    topicPosts: '/public/topic-posts',
    topicTree: '/public/topics-tree',
    relatedTopics: (slug: string) => `/public/related-topics/${slug}`,
    liveSources: "/public/live-sources",
    subscribe: "/public/subscribe",
    seo: (slug: string) => `public/seo/${slug}`,
    contact: "/public/contact",
  },
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    logout: "/auth/logout",
  },
  sitemap: {
    topics: '/public/topics/',
    posts: '/public/posts',
  },
  admin: {
    topic: (id: string) => "/topics/" + id,
    toggleTopicFeature: (id: string) => `/topics/${id}/toggle-featured`,
    topics: "/topics",
    topicTree: "/public/topics-tree",
    posts: "/posts",
    post: (id: string) => "/posts/" + id,
    collections: "/collections",
    comments: "/comments",
    ads: "/ads",
    ad: (id: string) => "/ads/" + id,
    collection: (id: string) => "/collections/" + id,
    upload: (type: string) => `/uploads?type=${type}`,
    feed: (id: string) => "/feeds/" + id,
    feeds: "/feeds",
    manageCollectionPosts: (collectionId: string) => `/collections/${collectionId}/manage-posts`,
    users: "/users",
    user: (id: string) => "/users/" + id,
    liveSources: "live-sources",
    liveSource: (id: string) => `live-sources/${id}`,
    seos: "seos",
    seo: (id: string) => `seos/${id}`,
    contactMessages: "contact-messages",
    contactMessage: (id: string) => `contact-messages/${id}`,
  },
  me: {
    base: '/me', 
    changePassword: "me/change-password",
    updateProfile: "me/update",
  },
}