export const APP_ROUTES = {
  home: '/',
  topic:  (slug: string) => '/topics/' + slug,
  post: (slug: string) => '/posts/' + slug,
  search: (q: string) => '/search?q=' + q,
  tags: (slug: string) => '/tags/' + slug,
  contact: '/contact',
  about: '/about',
  privacy: '/privacy',
  collection: (slug: string) => `/collections/${slug}`,
  source: (slug: string) => `/sources/${slug}`,
  admin: {
    dashboard: "/admin/dashboard",
    analytics: "/admin/analytics",
    topics: "/admin/topics",
    posts: "/admin/posts",
    profile: "/admin/profile",
    roles: "/admin/roles",
    settings: "/admin/settings",
    users: "/admin/users",
    collections: "/admin/collections",
    feeds: "/admin/feeds",
    forgotPassword: "/admin/forgot-password",
    ads: "/admin/ads",
    liveSources: "/admin/live-sources",
    staticPages: "/admin/static-pages",
    contactMessages:  "/admin/contact-messages",
    login: '/admin/login',
  }
}